### ISSUE TITLE
experiment group is problematic

### ISSUE THREAD

**Issue by lee212** [cloudmesh/cloudmesh#206]
get_mongo_db("experiment", DBConnFactory.TYPE_MONGOENGINE) fails.

The test command throws errors::
```
cm> group list
Failed to connect to MongoEngine DB:
	experiment
CM /cloudmesh-2.3.0-py2.7.egg/cloudmesh/config/cm_config.pyc... site:94:  ERROR - Failed to connect to MongoEngine DB:
	experiment
CM /cloudmesh-2.3.0-py2.7.egg/cloudmesh/config/cm_config.pyc... site:95:  ERROR - Traceback (most recent call last):
  File "/home/ubuntu/virtualenv/ENV/local/lib/python2.7/site-packages/cloudmesh-2.3.0-py2.7.egg/cloudmesh/config/cm_config.py", line 90, in getconn
    password=cls.DBCONFIG["password"])
  File "/home/ubuntu/virtualenv/ENV/local/lib/python2.7/site-packages/mongoengine/connection.py", line 164, in connect
    return get_connection(alias)
  File "/home/ubuntu/virtualenv/ENV/local/lib/python2.7/site-packages/mongoengine/connection.py", line 126, in get_connection
    raise ConnectionError("Cannot connect to database %s :\n%s" % (alias, e))
ConnectionError: Cannot connect to database experiment :
False is not a read preference.

CM /cloudmesh-2.3.0-py2.7.egg/cloudmesh/config/cm_config.pyc... site:125:  DEBUG - connection failed to experiment
ERROR: Cannot connect to database experiment : False is not a read preference.
```

**Comment by fugangwang** [comment]
appears to be caused by the pymongo compatibility issue when upgrading to 3.0.
I’m using 2.8 and I don’t see the error.
So, maybe at this point we again revert back to use pymongo 2.8 before we thoroughly address this issue. I’m modifying the requirements again.

**Comment by laszewsk** [comment]
please lets use 2.8 can you gues all update the requirements file from the various packages

**Comment by fugangwang** [comment]
I made the change on dev2.0 and merge it to master also.
I also made the same modification on the cloudmesh_base requirements.txt.

**Comment by fugangwang** [comment]
FYI. The issue:
https://github.com/MongoEngine/mongoengine/issues/935

**Comment by fugangwang** [comment]
For those who might have installed cloudmesh while we did not have pymongo version fixed to 2.8, in case they saw the problem, they should uninstall the installed pymongo first and then reinstall from our specified requirements.txt.

**Comment by laszewsk** [comment]
can you work out the final soultion, i will than also do a pypi update when you are done, than work on an announcement for the class just incase someone got stuck inbetween.

explain this is not our problem but an incompatibility in a packag ethat we use that was introcuded last week.

**Comment by fugangwang** [comment]
Well, in any case, this should ensure the right version of pymongo is being
used:
In cloudmesh git directory, when virtualenv is active:
git pull;
pip uninstall pymongo;
pip install -r requirements.txt

**Comment by fugangwang** [comment]
Alternatively, even if pymongo 3.0 is installed, a
pip install pymongo==2.8
would force downgrade the version.

These are all for those who had started the installation. For new users who
check out the new code and do a fresh install, the latest code already
restricted the pymongo version to 2.8.
